name: Flow
description: A simple StageXL web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Your Name <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
