name: Flow
description: Just a fun toy to play around with.
version: 1.0.0
homepage: https://mikefenwick.com
author: Mike Fenwick <mike@mikefenwick.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0
  color: ^2.1.0
  voronoi:
    git: git@github.com:MichaelFenwick/voronoi.git

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
